// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlimpicDb.Data;

#nullable disable

namespace OlimpicDb.Migrations
{
    [DbContext(typeof(OlimpicDbContext))]
    [Migration("20240429102107_ChangePlayerAndFilterCountryList2")]
    partial class ChangePlayerAndFilterCountryList2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OlimpicDb.Entity.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryFlagLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg/320px-Flag_of_Afghanistan_%282013%E2%80%932021%29.svg.png",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/320px-Flag_of_Albania.svg.png",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/320px-Flag_of_Algeria.svg.png",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/320px-Flag_of_American_Samoa.svg.png",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 5,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/320px-Flag_of_Andorra.svg.png",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/320px-Flag_of_Angola.svg.png",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/320px-Flag_of_Antigua_and_Barbuda.svg.png",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 8,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/320px-Flag_of_Argentina.svg.png",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 9,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/320px-Flag_of_Armenia.svg.png",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 10,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/320px-Flag_of_Aruba.svg.png",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 11,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/320px-Flag_of_Australia.svg.png",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 12,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/320px-Flag_of_Austria.svg.png",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 13,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/320px-Flag_of_Azerbaijan.svg.png",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 14,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/320px-Flag_of_the_Bahamas.svg.png",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 15,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/320px-Flag_of_Bahrain.svg.png",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 16,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/320px-Flag_of_Bangladesh.svg.png",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 17,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/320px-Flag_of_Barbados.svg.png",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 18,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/320px-Flag_of_Belarus.svg.png",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 19,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/320px-Flag_of_Belgium_%28civil%29.svg.png",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 20,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/320px-Flag_of_Belize.svg.png",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 21,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/320px-Flag_of_Benin.svg.png",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 22,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/320px-Flag_of_Bermuda.svg.png",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 23,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/320px-Flag_of_Bhutan.svg.png",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 24,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/320px-Flag_of_Bolivia.svg.png",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 25,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/320px-Flag_of_Bosnia_and_Herzegovina.svg.png",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 26,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/320px-Flag_of_Botswana.svg.png",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 27,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/320px-Flag_of_Brazil.svg.png",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 28,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/320px-Flag_of_the_British_Virgin_Islands.svg.png",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 29,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/320px-Flag_of_Brunei.svg.png",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 30,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/320px-Flag_of_Bulgaria.svg.png",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 31,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/320px-Flag_of_Burkina_Faso.svg.png",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 32,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/320px-Flag_of_Burundi.svg.png",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 33,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/320px-Flag_of_Cambodia.svg.png",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 34,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/320px-Flag_of_Cameroon.svg.png",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 35,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/320px-Flag_of_Canada_%28Pantone%29.svg.png",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 36,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/320px-Flag_of_Cape_Verde.svg.png",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 37,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Flag_of_the_Cayman_Islands_%28pre-1999%29.svg/320px-Flag_of_the_Cayman_Islands_%28pre-1999%29.svg.png",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 38,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/320px-Flag_of_the_Central_African_Republic.svg.png",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 39,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/320px-Flag_of_Chad.svg.png",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 40,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/320px-Flag_of_Chile.svg.png",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 41,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/320px-Flag_of_the_People%27s_Republic_of_China.svg.png",
                            Name = "China"
                        },
                        new
                        {
                            Id = 42,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Flag_of_Chinese_Taipei_for_Olympic_games.svg/320px-Flag_of_Chinese_Taipei_for_Olympic_games.svg.png",
                            Name = "Chinese Taipei"
                        },
                        new
                        {
                            Id = 43,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/320px-Flag_of_Colombia.svg.png",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 44,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/320px-Flag_of_the_Comoros.svg.png",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 45,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/320px-Flag_of_the_Cook_Islands.svg.png",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 46,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/320px-Flag_of_Costa_Rica.svg.png",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 47,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/320px-Flag_of_Croatia.svg.png",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 48,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/320px-Flag_of_Cuba.svg.png",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 49,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/320px-Flag_of_Cyprus.svg.png",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 50,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/320px-Flag_of_the_Czech_Republic.svg.png",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 51,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/320px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 52,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/320px-Flag_of_Denmark.svg.png",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 53,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/320px-Flag_of_Djibouti.svg.png",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 54,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/320px-Flag_of_Dominica.svg.png",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 55,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/320px-Flag_of_the_Dominican_Republic.svg.png",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 56,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/320px-Flag_of_East_Timor.svg.png",
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = 57,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/320px-Flag_of_Ecuador.svg.png",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 58,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/320px-Flag_of_Egypt.svg.png",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 59,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/320px-Flag_of_El_Salvador.svg.png",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 60,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/320px-Flag_of_Equatorial_Guinea.svg.png",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 61,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/320px-Flag_of_Eritrea.svg.png",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 62,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/320px-Flag_of_Estonia.svg.png",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 63,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/320px-Flag_of_Eswatini.svg.png",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 64,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/320px-Flag_of_Ethiopia.svg.png",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 65,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/320px-Flag_of_the_Federated_States_of_Micronesia.svg.png",
                            Name = "Federated States of Micronesia"
                        },
                        new
                        {
                            Id = 66,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/320px-Flag_of_Fiji.svg.png",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 67,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/320px-Flag_of_Finland.svg.png",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 68,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/320px-Flag_of_France.svg.png",
                            Name = "France"
                        },
                        new
                        {
                            Id = 69,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/320px-Flag_of_Gabon.svg.png",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 70,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/320px-Flag_of_Georgia.svg.png",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 71,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/320px-Flag_of_Germany.svg.png",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 72,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/320px-Flag_of_Ghana.svg.png",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 73,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/320px-Flag_of_the_United_Kingdom.svg.png",
                            Name = "Great Britain"
                        },
                        new
                        {
                            Id = 74,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/320px-Flag_of_Greece.svg.png",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 75,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/320px-Flag_of_Grenada.svg.png",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 76,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/320px-Flag_of_Guam.svg.png",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 77,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/320px-Flag_of_Guatemala.svg.png",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 78,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/320px-Flag_of_Guinea.svg.png",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 79,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/320px-Flag_of_Guinea-Bissau.svg.png",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 80,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/320px-Flag_of_Guyana.svg.png",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 81,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/320px-Flag_of_Haiti.svg.png",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 82,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Flag_of_Honduras_%281949%E2%80%932022%29.svg/320px-Flag_of_Honduras_%281949%E2%80%932022%29.svg.png",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 83,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/320px-Flag_of_Hong_Kong.svg.png",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 84,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/320px-Flag_of_Hungary.svg.png",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 85,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/320px-Flag_of_Iceland.svg.png",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 86,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/320px-Flag_of_India.svg.png",
                            Name = "India"
                        },
                        new
                        {
                            Id = 87,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/320px-Flag_of_Indonesia.svg.png",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 88,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/320px-Flag_of_Iran.svg.png",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 89,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/320px-Flag_of_Iraq.svg.png",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 90,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/320px-Flag_of_Ireland.svg.png",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 91,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/320px-Flag_of_Israel.svg.png",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 92,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/320px-Flag_of_Italy.svg.png",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 93,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/320px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 94,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/320px-Flag_of_Jamaica.svg.png",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 95,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/320px-Flag_of_Japan.svg.png",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 96,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/320px-Flag_of_Jordan.svg.png",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 97,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/320px-Flag_of_Kazakhstan.svg.png",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 98,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/320px-Flag_of_Kenya.svg.png",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 99,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/320px-Flag_of_Kiribati.svg.png",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 100,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Kosovo.svg/320px-Flag_of_Kosovo.svg.png",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 101,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/320px-Flag_of_Kuwait.svg.png",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 102,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Kyrgyzstan_%281992%E2%80%932023%29.svg/320px-Flag_of_Kyrgyzstan_%281992%E2%80%932023%29.svg.png",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 103,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/320px-Flag_of_Laos.svg.png",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 104,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/320px-Flag_of_Latvia.svg.png",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 105,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/320px-Flag_of_Lebanon.svg.png",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 106,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/320px-Flag_of_Lesotho.svg.png",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 107,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/320px-Flag_of_Liberia.svg.png",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 108,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/320px-Flag_of_Libya.svg.png",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 109,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/320px-Flag_of_Liechtenstein.svg.png",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 110,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/320px-Flag_of_Lithuania.svg.png",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 111,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/320px-Flag_of_Luxembourg.svg.png",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 112,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/320px-Flag_of_Madagascar.svg.png",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 113,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/320px-Flag_of_Malawi.svg.png",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 114,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/320px-Flag_of_Malaysia.svg.png",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 115,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/320px-Flag_of_Maldives.svg.png",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 116,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/320px-Flag_of_Mali.svg.png",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 117,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/320px-Flag_of_Malta.svg.png",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 118,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/320px-Flag_of_the_Marshall_Islands.svg.png",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 119,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/320px-Flag_of_Mauritania.svg.png",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 120,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/320px-Flag_of_Mauritius.svg.png",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 121,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/320px-Flag_of_Mexico.svg.png",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 122,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/320px-Flag_of_Moldova.svg.png",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 123,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/320px-Flag_of_Monaco.svg.png",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 124,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/320px-Flag_of_Mongolia.svg.png",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 125,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/320px-Flag_of_Montenegro.svg.png",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 126,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/320px-Flag_of_Morocco.svg.png",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 127,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/320px-Flag_of_Mozambique.svg.png",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 128,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/320px-Flag_of_Myanmar.svg.png",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 129,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/320px-Flag_of_Namibia.svg.png",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 130,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/320px-Flag_of_Nauru.svg.png",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 131,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/320px-Flag_of_Nepal.svg.png",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 132,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/320px-Flag_of_the_Netherlands.svg.png",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 133,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/320px-Flag_of_New_Zealand.svg.png",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 134,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/320px-Flag_of_Nicaragua.svg.png",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 135,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/320px-Flag_of_Niger.svg.png",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 136,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/320px-Flag_of_Nigeria.svg.png",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 137,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/320px-Flag_of_North_Macedonia.svg.png",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 138,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/320px-Flag_of_Norway.svg.png",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 139,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/320px-Flag_of_Oman.svg.png",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 140,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/320px-Flag_of_Pakistan.svg.png",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 141,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/320px-Flag_of_Palau.svg.png",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 142,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/320px-Flag_of_Palestine.svg.png",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 143,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/320px-Flag_of_Panama.svg.png",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 144,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/320px-Flag_of_Papua_New_Guinea.svg.png",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 145,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/320px-Flag_of_Paraguay.svg.png",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 146,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/320px-Flag_of_Peru.svg.png",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 147,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/320px-Flag_of_the_Philippines.svg.png",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 148,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/320px-Flag_of_Poland.svg.png",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 149,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/320px-Flag_of_Portugal.svg.png",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 150,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/320px-Flag_of_Puerto_Rico.svg.png",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 151,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/320px-Flag_of_Qatar.svg.png",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 152,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Olympic_flag.svg/320px-Olympic_flag.svg.png",
                            Name = "Refugee Olympic Team"
                        },
                        new
                        {
                            Id = 153,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/320px-Flag_of_the_Republic_of_the_Congo.svg.png",
                            Name = "Republic of the Congo"
                        },
                        new
                        {
                            Id = 154,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Russian_Olympic_Committee_flag.png/320px-Russian_Olympic_Committee_flag.png",
                            Name = "ROC"
                        },
                        new
                        {
                            Id = 155,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/320px-Flag_of_Romania.svg.png",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 156,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/320px-Flag_of_Rwanda.svg.png",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 157,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/320px-Flag_of_Saint_Kitts_and_Nevis.svg.png",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 158,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/320px-Flag_of_Saint_Lucia.svg.png",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 159,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/320px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 160,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/320px-Flag_of_Samoa.svg.png",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 161,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/320px-Flag_of_San_Marino.svg.png",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 162,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg/320px-Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg.png",
                            Name = "São Tomé and Príncipe"
                        },
                        new
                        {
                            Id = 163,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/320px-Flag_of_Saudi_Arabia.svg.png",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 164,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/320px-Flag_of_Senegal.svg.png",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 165,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/320px-Flag_of_Israel.svg.png",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 166,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/320px-Flag_of_Seychelles.svg.png",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 167,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/320px-Flag_of_Sierra_Leone.svg.png",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 168,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/320px-Flag_of_Singapore.svg.png",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 169,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/320px-Flag_of_Slovakia.svg.png",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 170,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/320px-Flag_of_Slovenia.svg.png",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 171,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/320px-Flag_of_the_Solomon_Islands.svg.png",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 172,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/320px-Flag_of_Somalia.svg.png",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 173,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/320px-Flag_of_South_Africa.svg.png",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 174,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/320px-Flag_of_South_Korea.svg.png",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 175,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/320px-Flag_of_South_Sudan.svg.png",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 176,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/320px-Flag_of_Spain.svg.png",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 177,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/320px-Flag_of_Sri_Lanka.svg.png",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 178,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/320px-Flag_of_Sudan.svg.png",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 179,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/320px-Flag_of_Suriname.svg.png",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 180,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/320px-Flag_of_Sweden.svg.png",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 181,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/320px-Flag_of_Switzerland.svg.png",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 182,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/320px-Flag_of_Syria.svg.png",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 183,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/320px-Flag_of_Tajikistan.svg.png",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 184,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/320px-Flag_of_Tanzania.svg.png",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 185,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/320px-Flag_of_Thailand.svg.png",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 186,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/320px-Flag_of_The_Gambia.svg.png",
                            Name = "The Gambia"
                        },
                        new
                        {
                            Id = 187,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/320px-Flag_of_Togo.svg.png",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 188,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/320px-Flag_of_Tonga.svg.png",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 189,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/320px-Flag_of_Trinidad_and_Tobago.svg.png",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 190,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/320px-Flag_of_Tunisia.svg.png",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 191,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/320px-Flag_of_Turkey.svg.png",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 192,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/320px-Flag_of_Turkmenistan.svg.png",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 193,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/320px-Flag_of_Tuvalu.svg.png",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 194,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/320px-Flag_of_Uganda.svg.png",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 195,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/320px-Flag_of_Ukraine.svg.png",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 196,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/320px-Flag_of_the_United_Arab_Emirates.svg.png",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 197,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/320px-Flag_of_the_United_States.svg.png",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 198,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/320px-Flag_of_Uruguay.svg.png",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 199,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/320px-Flag_of_Uzbekistan.svg.png",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 200,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/320px-Flag_of_Vanuatu.svg.png",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 201,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Flag_of_Venezuela_%28state%29.svg/320px-Flag_of_Venezuela_%28state%29.svg.png",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 202,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/320px-Flag_of_Vietnam.svg.png",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 203,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/320px-Flag_of_the_United_States_Virgin_Islands.svg.png",
                            Name = "Virgin Islands"
                        },
                        new
                        {
                            Id = 204,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/320px-Flag_of_Yemen.svg.png",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 205,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/320px-Flag_of_Zambia.svg.png",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 206,
                            CountryFlagLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/320px-Flag_of_Zimbabwe.svg.png",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("OlimpicDb.Entity.OlimpicGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.ToTable("OlimpicGames");
                });

            modelBuilder.Entity("OlimpicDb.Entity.OlimpicGameSport", b =>
                {
                    b.Property<int>("OlimpicGameId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("OlimpicGameId", "SportId");

                    b.HasIndex("SportId");

                    b.ToTable("OlimpicGameSports");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OlimpicGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("OlimpicDb.Entity.PlayerOlimpicGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("OlimpicGameId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "OlimpicGameId");

                    b.HasIndex("OlimpicGameId");

                    b.ToTable("PlayerOlimpicGames");
                });

            modelBuilder.Entity("OlimpicDb.Entity.PlayerSport", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "SportId");

                    b.HasIndex("SportId");

                    b.ToTable("PlayerSports");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SportId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("OlimpicDb.Entity.OlimpicGame", b =>
                {
                    b.HasOne("OlimpicDb.Entity.Place", "Place")
                        .WithOne("OlimpicGame")
                        .HasForeignKey("OlimpicDb.Entity.OlimpicGame", "PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("OlimpicDb.Entity.OlimpicGameSport", b =>
                {
                    b.HasOne("OlimpicDb.Entity.OlimpicGame", "OlimpicGame")
                        .WithMany("OlimpicGameSports")
                        .HasForeignKey("OlimpicGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlimpicDb.Entity.Sport", "Sport")
                        .WithMany("OlimpicGameSports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OlimpicGame");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Place", b =>
                {
                    b.HasOne("OlimpicDb.Entity.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OlimpicDb.Entity.PlayerOlimpicGame", b =>
                {
                    b.HasOne("OlimpicDb.Entity.OlimpicGame", "OlimpicGame")
                        .WithMany("PlayerOlimpicGames")
                        .HasForeignKey("OlimpicGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlimpicDb.Entity.Player", "Player")
                        .WithMany("PlayerOlimpicGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OlimpicGame");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OlimpicDb.Entity.PlayerSport", b =>
                {
                    b.HasOne("OlimpicDb.Entity.Player", "Player")
                        .WithMany("PlayerSports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlimpicDb.Entity.Sport", "Sport")
                        .WithMany("PlayerSports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Statistic", b =>
                {
                    b.HasOne("OlimpicDb.Entity.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlimpicDb.Entity.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("OlimpicDb.Entity.OlimpicGame", b =>
                {
                    b.Navigation("OlimpicGameSports");

                    b.Navigation("PlayerOlimpicGames");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Place", b =>
                {
                    b.Navigation("OlimpicGame")
                        .IsRequired();
                });

            modelBuilder.Entity("OlimpicDb.Entity.Player", b =>
                {
                    b.Navigation("PlayerOlimpicGames");

                    b.Navigation("PlayerSports");
                });

            modelBuilder.Entity("OlimpicDb.Entity.Sport", b =>
                {
                    b.Navigation("OlimpicGameSports");

                    b.Navigation("PlayerSports");
                });
#pragma warning restore 612, 618
        }
    }
}
